[package]
name = "Micrograd-in-Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
rand_distr = "0.5"
polars = { version = "0.50", features = ["lazy", "fmt"] }
plotly = "0.10"
plotters = { version = "0.3", default-features = false, features = ["svg_backend"] }
